// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Feed struct {
	ID        int64
	Name      string
	Url       string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Post struct {
	ID     int64
	Title  string
	Url    string
	Saved  sql.NullBool
	Viewed time.Time
}

type SavedPost struct {
	ID        int64
	Title     string
	Url       string
	Feed      string
	CreatedAt time.Time
}
