// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createPost = `-- name: CreatePost :exec
INSERT INTO posts (
    feed_id,
    title,
    url,
    content,
    published_at,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
) RETURNING id, feed_id, title, url, content, published_at, created_at
`

type CreatePostParams struct {
	FeedID      int64
	Title       string
	Url         string
	Content     sql.NullString
	PublishedAt time.Time
	CreatedAt   time.Time
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.ExecContext(ctx, createPost,
		arg.FeedID,
		arg.Title,
		arg.Url,
		arg.Content,
		arg.PublishedAt,
		arg.CreatedAt,
	)
	return err
}

const getPostById = `-- name: GetPostById :one
SELECT id, feed_id, title, url, content, published_at, created_at FROM posts WHERE id = ?
`

func (q *Queries) GetPostById(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostById, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Title,
		&i.Url,
		&i.Content,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPostByUrl = `-- name: GetPostByUrl :one
SELECT id, feed_id, title, url, content, published_at, created_at FROM posts WHERE url = ?
`

func (q *Queries) GetPostByUrl(ctx context.Context, url string) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostByUrl, url)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Title,
		&i.Url,
		&i.Content,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPostsByFeedId = `-- name: GetPostsByFeedId :many
SELECT id, feed_id, title, url, content, published_at, created_at FROM posts 
WHERE feed_id = ? 
ORDER BY published_at DESC
`

func (q *Queries) GetPostsByFeedId(ctx context.Context, feedID int64) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostsByFeedId, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Url,
			&i.Content,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentPosts = `-- name: GetRecentPosts :many
SELECT p.id, p.feed_id, p.title, p.url, p.content, p.published_at, p.created_at, f.name as feed_name, f.url as feed_url
FROM posts p
JOIN feeds f ON p.feed_id = f.id
ORDER BY published_at DESC
LIMIT ?
`

type GetRecentPostsRow struct {
	ID          int64
	FeedID      int64
	Title       string
	Url         string
	Content     sql.NullString
	PublishedAt time.Time
	CreatedAt   time.Time
	FeedName    string
	FeedUrl     string
}

func (q *Queries) GetRecentPosts(ctx context.Context, limit int64) ([]GetRecentPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentPosts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentPostsRow
	for rows.Next() {
		var i GetRecentPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Url,
			&i.Content,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.FeedName,
			&i.FeedUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
