name: Release Build

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Build for Windows, Linux, and macOS
        goos: [windows, linux, darwin]
        goarch: [amd64, arm64]
        exclude:
          # Exclude arm64 build for windows
          - goarch: arm64
            goos: windows

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Set up dependencies for Windows
      if: matrix.goos == 'windows'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-mingw-w64
        sudo apt-get install -y gcc-multilib
        sudo apt-get install -y libsqlite3-dev

    - name: Set up dependencies for Linux
      if: matrix.goos == 'linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc
        sudo apt-get install -y libsqlite3-dev

    - name: Set up dependencies for macOS
      if: matrix.goos == 'darwin'
      run: |
        sudo apt-get update
        sudo apt-get install -y clang
        sudo apt-get install -y libsqlite3-dev

    - name: Build Windows Binary
      if: matrix.goos == 'windows'
      env:
        CGO_ENABLED: 1
        GOOS: windows
        GOARCH: ${{ matrix.goarch }}
        CC: x86_64-w64-mingw32-gcc
      run: |
        go build -o rssdukester.exe

    - name: Build Unix Binary
      if: matrix.goos != 'windows'
      env:
        CGO_ENABLED: 1
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        go build -o rssdukester

    - name: Package Windows Release
      if: matrix.goos == 'windows'
      run: |
        zip "rssdukester-${{ matrix.goos }}-${{ matrix.goarch }}.zip" rssdukester.exe

    - name: Package Unix Release
      if: matrix.goos != 'windows'
      run: |
        tar czf "rssdukester-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz" rssdukester

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          rssdukester-${{ matrix.goos }}-${{ matrix.goarch }}.*
